### ISSUE TITLE
Init container requires root

### ISSUE THREAD

**Issue by mook-as** [SUSE/eirini-persi#24]
In [`VcapServices.AppendMounts()`] we create an init container that needs to run as root (to run `chmod` to ensure the mount has the correct permissions). However, [`StatefulSetDesirer.getGetSecurityContext()`] can (at least in the cases I tested) end up with a security context of `runAsNonRoot: true`.

This leads to the pod not starting, with an error message of `Error: container's runAsUser breaks non-root policy`.

[`VcapServices.AppendMounts()`]: https://github.com/SUSE/eirini-persi/blob/2074eb02955953e77b4c20855a8ed1ced4808318/extensions/persistence/persistence.go#L71-L72
[`StatefulSetDesirer.getGetSecurityContext()`]: https://github.com/cloudfoundry-incubator/eirini/blob/1.5.0/k8s/statefulset.go#L609

**Comment by viovanov** [comment]
We should try to also mutate `fsGroup` as mentioned here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#podsecuritycontext-v1-core

also see https://github.com/kubernetes/kubernetes/issues/2630

**Comment by viovanov** [comment]
closing in favor of https://github.com/cloudfoundry-incubator/kubecf/issues/782
